# Generated by Django 4.2.4 on 2023-08-24 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='guests',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
