# Generated by Django 4.2.4 on 2023-08-31 15:21

import core.utils.time
import datetime
from django.db import migrations, models
import django.db.models.deletion
import reservations.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rooms', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_guests', models.PositiveSmallIntegerField(default=1, verbose_name='Number Of Guests')),
                ('check_in', models.DateField(default=core.utils.time.get_default_checkin)),
                ('check_out', models.DateField(default=core.utils.time.get_default_checkout)),
                ('arrival_time', models.TimeField(default=datetime.time(15, 0))),
                ('notes', models.TextField(blank=True, max_length=400, null=True)),
                ('requested_on', models.DateField(auto_now_add=True)),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Requested'), (2, 'Confirmed'), (3, 'Cancelled')], default=1)),
                ('confirmation_code', models.CharField(default=reservations.models.generate_unique_code, max_length=8, unique=True)),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.guest')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooms.room')),
            ],
            options={
                'verbose_name': 'Reservation',
                'verbose_name_plural': 'Reservations',
            },
        ),
    ]
