# Generated by Django 4.2.4 on 2023-08-24 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True, help_text='Max 300 characters', max_length=300, null=True)),
                ('icon', models.CharField(blank=True, help_text="Font Awesome class format ex. 'fa-solid fa-check'", max_length=100, null=True)),
            ],
        ),
    ]
