# Generated by Django 4.2.4 on 2023-08-31 15:21

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GuestAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=200)),
                ('street_number', models.CharField(max_length=200)),
                ('postcode', models.CharField(max_length=6)),
                ('city', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('pref_arrival_time', models.TimeField(default=datetime.time(15, 0), verbose_name='Preferred Arrival Time')),
                ('min_staying_duration', models.DurationField(default=datetime.timedelta(days=2), verbose_name='Minimum Booking Nights')),
                ('max_staying_duration', models.DurationField(default=datetime.timedelta(days=30), verbose_name='Maximum Booking Nights')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True, help_text='Max 300 characters', max_length=300, null=True)),
                ('icon', models.CharField(blank=True, help_text="Font Awesome class format ex. 'fa-solid fa-check'", max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('address', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.guestaddress')),
            ],
        ),
    ]
