# Generated by Django 4.2.4 on 2023-08-24 18:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('pref_arrival_time', models.TimeField(default=datetime.time(15, 0))),
                ('min_staying_duration', models.IntegerField(default=2)),
                ('max_staying_duration', models.IntegerField(default=30)),
            ],
        ),
    ]
