# Generated by Django 4.2.4 on 2023-08-24 19:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_hotel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='max_staying_duration',
            field=models.IntegerField(default=datetime.timedelta(days=30), verbose_name='Maximum Booking Nights'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='min_staying_duration',
            field=models.DurationField(default=datetime.timedelta(days=2), verbose_name='Minimum Booking Nights'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='pref_arrival_time',
            field=models.TimeField(default=datetime.time(15, 0), verbose_name='Preferred Arrival Time'),
        ),
    ]
