# Generated by Django 4.2.4 on 2023-08-24 19:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_hotel_max_staying_duration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='max_staying_duration',
            field=models.DurationField(default=datetime.timedelta(days=30), verbose_name='Maximum Booking Nights'),
        ),
    ]
